#!/usr/bin/env python3
print("=" * 60)
print("Eitaa Automation Script - Demo Mode")
print("=" * 60)
print()
print("This automation script is designed for Windows systems")
print("with Google Chrome installed.")
print()
print("IMPORTANT:")
print("- This script CANNOT run in Replit due to headless")
print("  browser limitations")
print("- The Eitaa website blocks headless Chrome browsers")
print()
print("To use this script on your Windows computer:")
print()
print("METHOD 1 - AUTOMATIC SETUP (RECOMMENDED):")
print("  1. Download all files to your Windows computer")
print("  2. Double-click setup.bat file")
print("  3. Follow the instructions")
print("  4. Run: python eitaa_automation.py")
print()
print("METHOD 2 - MANUAL SETUP:")
print("  1. Download all files to your Windows computer")
print("  2. Install Python 3.11+ and Google Chrome")
print("  3. Run: pip install -r requirements.txt")
print("  4. Run: python eitaa_automation.py")
print()
print("With custom phone number:")
print("   python eitaa_automation.py 9101234567")
print()
print("=" * 60)
print("Files in this project:")
print("  - eitaa_automation.py  (main automation script)")
print("  - setup.bat            (automatic installer for Windows)")
print("  - setup.py             (automatic installer for all OS)")
print("  - requirements.txt     (Python dependencies)")
print("  - README.md            (full Persian documentation)")
print("=" * 60)
